apiVersion: v1
kind: Service
metadata:
  name: {{ include "kantele.fullname" . }}
  labels:
    {{- include "kantele.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kantele.selectorLabels" . | nindent 4 }}
  ports:
    - port: 4444
      targetPort: telnet
      protocol: TCP
      name: telnet
